Core 448
commonsku/commonsku-styles pull request #229
Opened 2024-01-12 15:38 UTC by andy-commonsku

2024-01-12 22:13 UTC, robert-commonsku requested changes

2024-01-12 22:13 UTC, robert-commonsku commented on src/@commonsku/styles/tables/VirtualTable.tsx
> +  onSortChange?: (sortState: UseSortByState<RowType>) => void;
I don't think that any code is using the `onSort` prop.  Can you get rid of it?  I think it's confusing to have both `onSortChange` and `onSort` with slightly different semantics.

2024-01-12 22:13 UTC, robert-commonsku commented on src/@commonsku/styles/tables/types.ts
Can you remove this file from the PR?

2024-01-15 15:36 UTC, andy-commonsku commented on src/@commonsku/styles/tables/types.ts
I copied the raw file from maser but still got the changes here
did not use format tool on this

2024-01-15 21:49 UTC, robert-commonsku approved these changes

2024-01-15 21:49 UTC, merged