added typography component
commonsku/commonsku-styles pull request #233
Opened 2024-01-23 22:09 UTC by hasahmad

2024-02-13 19:45 UTC, robert-commonsku requested changes

2024-02-13 19:45 UTC, robert-commonsku commented on src/@commonsku/styles/Typography.tsx
This seems to duplicate some of the functionality from `Headers.tsx`.   It probably isn't great to have multiple `H1`, `H2`, etc. components.  Is there a way we can reconcile these?  They seem to have different styling.

2024-02-13 21:10 UTC, hasahmad commented on src/@commonsku/styles/Typography.tsx
Yes, I'm aware of it but the those components are being used would require a refactor throughout the app. I think we should use these starting now. We can later gradually move components using the other Headings components to this one

2024-02-21 17:04 UTC, robert-commonsku approved these changes

2024-02-21 19:59 UTC, robert-commonsku approved these changes

2024-02-21 20:12 UTC, merged